---
title: "My awesome website"
output: 
  html_document:
    toc: true
    toc_float: true
---

# Welcome to my awesome website!!!

# Here's some info about me and a plot job.

# Here is some methods about the process of data analysis:

I'm interested in the different kinds of cuisine in MANHATTAN and other cities in NY as well as their scores. 


## step1
After cleaning the name of the Data set and some meaningless lines of scores that are NA, I select select the data that their city is MANHATTAN and Study the relationship between their cuisine and ratings.

What I focus on is the relationship between the types of dishes that each piece of data represents and their ratings. And try to pick out the more popular dishes in the data.

From the pictures, we can see that in Manhattan all kinds of dishes, excluded Basque, are regular and good. The average score of the dishes is the highest. Another point is that we can see that the most popular food in the data set is American food, followed by Chinese food, and still more popular: Korea, Japan, pizza

## step2
Further I would like to look at the ratings of the more popular dishes in Manhattan from the US, China and Japan across all cities.

From the graph we can first see that those with a grades of A make up the vast majority of restaurants with each cuisine. And this trend is evident in American cuisine.

It is not difficult to see from the figure that the scores of restaurants fluctuate periodically over time, and there is an extreme value in 2014-15 and after 2017. And numerically, the score of DUNKIN'DONUTS is higher.

## step3
Ultimately I want to look at the scores of the top three restaurants in the dataset in terms of American cuisine.